#!/usr/bin/env python3
"""Generate src/Tuinet/Internal/UnicodeWidth.g.cs from the Unicode Character Database.

Usage: tools/gen-width/gen.py [UCD_VERSION]   (default 17.0.0; downloads into a temp dir)

Width rules (terminal column count, wcwidth-compatible):
  0  controls (Cc), combining marks (Mn, Me), format chars (Cf) except prepended
     concatenation marks and SOFT HYPHEN, line/paragraph separators, Hangul medial/final jamo
  2  East_Asian_Width W or F, or Emoji_Presentation=Yes
  1  everything else (including ambiguous and unassigned non-wide code points)
"""
import os, sys, tempfile, urllib.request

VERSION = sys.argv[1] if len(sys.argv) > 1 else "17.0.0"
BASE = f"https://www.unicode.org/Public/{VERSION}/ucd/"
FILES = ["EastAsianWidth.txt", "emoji/emoji-data.txt", "extracted/DerivedGeneralCategory.txt"]
ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
OUT = os.path.join(ROOT, "src", "Tuinet", "Internal", "UnicodeWidth.g.cs")
MAX = 0x110000
BLOCK = 256

def fetch(name, cache):
    path = os.path.join(cache, os.path.basename(name))
    if not os.path.exists(path):
        urllib.request.urlretrieve(BASE + name, path)
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.split("#", 1)[0].strip()
            if not line:
                continue
            cps, value = [p.strip() for p in line.split(";")[:2]]
            lo, _, hi = cps.partition("..")
            yield int(lo, 16), int(hi or lo, 16), value

def main():
    cache = os.environ.get("UCD_DIR") or tempfile.mkdtemp(prefix="ucd-")
    width = bytearray([1]) * MAX

    for lo, hi, eaw in fetch(FILES[0], cache):
        if eaw in ("W", "F"):
            width[lo:hi + 1] = b"\x02" * (hi - lo + 1)
    for lo, hi, prop in fetch(FILES[1], cache):
        if prop == "Emoji_Presentation":
            width[lo:hi + 1] = b"\x02" * (hi - lo + 1)

    keep = {0x00AD, 0x0600, 0x0601, 0x0602, 0x0603, 0x0604, 0x0605, 0x06DD, 0x070F,
            0x0890, 0x0891, 0x08E2, 0x110BD, 0x110CD}
    for lo, hi, gc in fetch(FILES[2], cache):
        if gc in ("Cc", "Mn", "Me", "Cf", "Zl", "Zp", "Cs"):
            for cp in range(lo, hi + 1):
                if cp not in keep:
                    width[cp] = 0
    for lo, hi in ((0x1160, 0x11FF), (0xD7B0, 0xD7FF)):
        width[lo:hi + 1] = b"\x00" * (hi - lo + 1)

    blocks, index = {}, []
    for start in range(0, MAX, BLOCK):
        packed = bytearray(BLOCK // 4)
        for i in range(BLOCK):
            packed[i >> 2] |= width[start + i] << ((i & 3) * 2)
        packed = bytes(packed)
        index.append(blocks.setdefault(packed, len(blocks)))
    assert len(blocks) <= 256, len(blocks)
    stage2 = b"".join(sorted(blocks, key=blocks.get))

    def rows(data, per=32):
        return "\n".join("        " + ", ".join(f"0x{b:02X}" for b in data[i:i + per]) + ","
                         for i in range(0, len(data), per))

    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(f"""// <auto-generated>
// Generated by tools/gen-width/gen.py from Unicode {VERSION} UCD. Do not edit.
// </auto-generated>
namespace Tuinet;

internal static partial class UnicodeWidth
{{
    public const string UnicodeVersion = "{VERSION}";

    // Stage 1: one byte per 256-code-point block, indexing a stage-2 block.
    private static ReadOnlySpan<byte> Stage1 => new byte[]
    {{
{rows(bytes(index))}
    }};

    // Stage 2: {len(blocks)} unique blocks, 2 bits per code point (64 bytes per block).
    private static ReadOnlySpan<byte> Stage2 => new byte[]
    {{
{rows(stage2)}
    }};
}}
""")
    print(f"wrote {OUT}: {len(blocks)} blocks, {len(index) + len(stage2)} bytes")

if __name__ == "__main__":
    main()
